
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surya
 */
public class showSubject extends javax.swing.JInternalFrame {

    /**
     * Creates new form showSubject
     */
    Connection x;
    String Tid;
    String Rollno;
    String SubjectId;
    public showSubject(Connection x,String Tid) {
        initComponents();
        this.x=x;
        this.Tid=Tid;
        showSubject();
       // p2.setVisible(false);
         
        
    }
    void showSubject()
    {
    
    try
    {
        Vector heading=new Vector();
    heading.add("DeptId");
    heading.add("CourseId");
     heading.add("BatchId");
     heading.add("Sem");
      heading.add("SectionId");
       heading.add("SubjectId");
      
Vector data=new Vector(); 
        String SectionId=null;
        String SubjectId=null;
     String query="select section_id,subject_id from sa where teacher_id=?";
        PreparedStatement ps=x.prepareStatement(query);
        ps.setString(1,Tid);
        ResultSet rs=ps.executeQuery();
       while(rs.next())
        {
        SectionId=rs.getString("section_id");
        SubjectId=rs.getString("subject_id");
        int Sem=0;
       String BatchId=null;
        
       String query2="select batch_id,sem from section where section_id=?";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,SectionId);
        ResultSet rs2=ps2.executeQuery();
       if(rs2.next())
        {
        BatchId=rs2.getString("batch_id");
        Sem=rs2.getInt("sem");
        }
         String CourseId=null;
         String query3="select course_id from batch where batch_id=?";
        PreparedStatement ps3=x.prepareStatement(query3);
        ps3.setString(1,BatchId);
        ResultSet rs3=ps3.executeQuery();
        if(rs3.next())
        {
        
        CourseId=rs3.getString("course_id");
        }
        String DeptId=null;
        String query4="select dept_id from course where course_id=?";
        PreparedStatement ps4=x.prepareStatement(query4);
        ps4.setString(1,CourseId);
        ResultSet rs4=ps4.executeQuery();
        if(rs4.next())
        {
        DeptId=rs4.getString("dept_id");
        }
        Vector row=new Vector();
row.add(DeptId);
row.add(CourseId);
row.add(BatchId);
row.add(Sem);
row.add(SectionId);
row.add(SubjectId);
data.add(row);        
        }
        
            
  


DefaultTableModel d=new DefaultTableModel(data,heading);
jTable1.setModel(d);

        }
       
     
    catch(Exception e)
    {
    e.printStackTrace();
    }
    }
    
    
    
      public void setAttendance(JTable table,
                                 TableColumn sportColumn) {
        //Set up the editor for the sport cells.
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("Present");
        comboBox.addItem("Absent");
       
        sportColumn.setCellEditor(new DefaultCellEditor(comboBox));

        //Set up tool tips for the sport cells.
        DefaultTableCellRenderer renderer =
                new DefaultTableCellRenderer();
        renderer.setToolTipText("Mark Attendance");
        sportColumn.setCellRenderer(renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        UpdateButton = new javax.swing.JButton();
        p1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "rollno", "Name", "choice"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(UpdateButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(UpdateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DeptId", "CourseId", "Batchid", "Sem", "Sectionid", "Subjectid"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jLabel1.setText("Show_AssignedSubject");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)))
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(602, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try
        {
            // p1.setVisible(false);
         //  p2.setVisible(true);
            
          
            int index=jTable1.getSelectedRow();
             
            if(index<0)
            {
                JOptionPane.showMessageDialog(this, "Select Again");
            return;    
            }
            
            
        TableModel tm = jTable1.getModel();
             String SectionId= (String)tm.getValueAt(index,4);
             SubjectId= (String)tm.getValueAt(index,5);

            
        Vector heading=new Vector();
    heading.add("Rollno");
    heading.add("Name");
     heading.add("Attendance");
  
     String query2="select rollno,name from student where section_id=?";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,SectionId);
        ResultSet rs2=ps2.executeQuery();
    Vector data=new Vector();  
        while(rs2.next())
        {
            Vector row=new Vector();
        row.add(rs2.getString("rollno"));
        row.add(rs2.getString("name")); 
         row.add("Present"); 
        data.add(row);
        }
       DefaultTableModel d=new DefaultTableModel(data,heading);
       jTable2.setModel(d);
       
       setAttendance(jTable2, jTable2.getColumnModel().getColumn(2));
     
//  Vector data=new Vector();    
//         while (rs2.next()) {
//               Vector row=new Vector();
//                model.addRow(new Object[]{rs2.getString("rollno"), rs2.getString("name"),false});
//
//            }
//DefaultTableModel model = new DefaultTableModel();
//
//           jTable2.setModel(model);
        }
    catch(Exception e)
    {
    e.printStackTrace();
    }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        try
        {
        int row=jTable2.getRowCount();
        TableModel tm = jTable2.getModel();
          Date d=jXDatePicker1.getDate();
        
        SimpleDateFormat sd=new SimpleDateFormat("dd/MM/yy");
       // System.out.print(d);
        
        String cdate=sd.format(d);
        
        for(int i=0;i<row;i++)
        {
         
             String Rollno= (String)tm.getValueAt(i,0);
             String Status= (String)tm.getValueAt(i,2);
             String query5="insert into attendance(teacher_id,student_id,subject_id,date,status)values(?,?,?,?,?)";
        PreparedStatement ps5=x.prepareStatement(query5);
        ps5.setString(1,Tid);
          ps5.setString(2,Rollno);
           ps5.setString(3,SubjectId);
            ps5.setString(4,cdate);
             ps5.setString(5,Status);
           
        int chk=ps5.executeUpdate();
      
        }
         JOptionPane.showMessageDialog(this,"Attendance updated");
            
        }
        catch(Exception e)
        {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,"something wrong");
        
        }
        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    // End of variables declaration//GEN-END:variables
}
