
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surya
 */
public class Student extends javax.swing.JInternalFrame {

    /**
     * Creates new form Student
     */
    Connection x;
     ArrayList Sectiondata=new ArrayList();
    public Student(Connection x) {
        initComponents();
        this.x=x;
        fill_Combobox();
        showdata();
    }
    void fill_Combobox()
    {
    
         try
        {
          
        
        String query="select * from department";
        PreparedStatement ps=x.prepareStatement(query);
        ResultSet rs=ps.executeQuery();
        while(rs.next())
        {
        cmb_DeptName.addItem(rs.getString("dept_name"));
        // DeptId=rs.getString("dept_id");
         
        }
        }
    catch(Exception e)
    {
    e.printStackTrace();}
    
    }
    void showdata()
    {
    
        try
    {
    Vector heading=new Vector();
    heading.add("Rollno");
    heading.add("SectionId");
     heading.add("Name");
      heading.add("Fname");
     heading.add("Contactno");
String query="select * from student";
PreparedStatement ps=x.prepareStatement(query);
ResultSet rs=ps.executeQuery();
Vector data=new Vector();     
while(rs.next())
{
  
Vector row=new Vector();
row.add(rs.getString("rollno"));
row.add(rs.getString("section_id"));
row.add(rs.getString("name"));
row.add(rs.getString("fname"));
row.add(rs.getString("contactno"));
data.add(row);

}
DefaultTableModel d=new DefaultTableModel(data,heading);
jTable1.setModel(d);

}
    catch(Exception e)
    {
    e.printStackTrace();
    }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb_DeptName = new javax.swing.JComboBox<>();
        cmb_CourseName = new javax.swing.JComboBox<>();
        cmb_BatchName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Rollno = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        txt_Fname = new javax.swing.JTextField();
        txt_Contactno = new javax.swing.JTextField();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_SectionName = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("DeptName");

        jLabel2.setText("CourseName");

        jLabel3.setText("Batch");

        cmb_DeptName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmb_DeptName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_DeptNameItemStateChanged(evt);
            }
        });

        cmb_CourseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmb_CourseName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CourseNameItemStateChanged(evt);
            }
        });

        cmb_BatchName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmb_BatchName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_BatchNameItemStateChanged(evt);
            }
        });

        jLabel4.setText("Rollno");

        Name.setText("Name");

        jLabel6.setText("Fname");

        jLabel7.setText("Contactno");

        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });

        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rollno", "SectionId", "Name", "Fname", "Contactno"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("Student");

        jLabel5.setText("Section");

        cmb_SectionName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(Name)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateButton)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(DeleteButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmb_SectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmb_DeptName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmb_CourseName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmb_BatchName, 0, 101, Short.MAX_VALUE)
                                        .addComponent(txt_Rollno)
                                        .addComponent(txt_Name)
                                        .addComponent(txt_Fname)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Contactno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_DeptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_CourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cmb_BatchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_SectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Rollno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Contactno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(InsertButton)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void cmb_DeptNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_DeptNameItemStateChanged
        // TODO add your handling code here:
        try
        {
            cmb_CourseName.removeAllItems();
            String DeptId=null;
            String DeptName=(String) cmb_DeptName.getSelectedItem();
        String query="select dept_id from department where dept_name=?";
        PreparedStatement ps=x.prepareStatement(query);
        ps.setString(1,DeptName);
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        {
        DeptId=rs.getString("dept_id");
         
        }
         String query2="select course_name from course where dept_id=?";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,DeptId);
        ResultSet rs2=ps2.executeQuery();
        while(rs2.next())
        {
        cmb_CourseName.addItem(rs2.getString("course_name"));
         
        }
        
        
        
        }
        
    catch(Exception e)
    {
    e.printStackTrace();
    }
    }//GEN-LAST:event_cmb_DeptNameItemStateChanged

    private void cmb_CourseNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CourseNameItemStateChanged
        // TODO add your handling code here:
        try
        {
            cmb_BatchName.removeAllItems();
            String CourseId=null;
            String CourseName=(String) cmb_CourseName.getSelectedItem();
        String query="select course_id from course where course_name=?";
        PreparedStatement ps=x.prepareStatement(query);
        ps.setString(1,CourseName);
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        {
        CourseId=rs.getString("course_id");
         
        }
         String query2="select batch_name from batch where course_id=?";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,CourseId);
        ResultSet rs2=ps2.executeQuery();
        while(rs2.next())
        {
        cmb_BatchName.addItem(rs2.getString("batch_name"));
         
        }
        
        
        
        }
        
    catch(Exception e)
    {
    e.printStackTrace();
    }
    }//GEN-LAST:event_cmb_CourseNameItemStateChanged

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        
        try
        {
            
            String SectionName=(String) cmb_SectionName.getSelectedItem();
        String Rollno=(String) txt_Rollno.getText();
        String Name=(String) txt_Name.getText();
        String Fname=(String) txt_Fname.getText();
        String Contactno=(String) txt_Contactno.getText();
        
       int Sectionindex=cmb_SectionName.getSelectedIndex();
            String x1[]=(String []) Sectiondata.get(Sectionindex);
            String SectionId=x1[0];
        
       
        String query2="insert into student(rollno,section_id,name,fname,contactno)values(?,?,?,?,?)";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,Rollno);
        ps2.setString(2,SectionId);
        ps2.setString(3,Name);
        ps2.setString(4,Fname);
        ps2.setString(5,Contactno);
        
        int chk=ps2.executeUpdate();
        JOptionPane.showMessageDialog(this,"data inserted");
        showdata();
        
        }
        
        catch(Exception e)
        {
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(this,"data can't be inserted. "+e.getMessage());
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
      try
        {
            
        int index=jTable1.getSelectedRow();
        TableModel tm = jTable1.getModel();
       
        String Rollno= (String)tm.getValueAt(index,0);
        String SectionId= (String)tm.getValueAt(index,1);
        String Name = (String)tm.getValueAt(index,2);
         String Fname = (String)tm.getValueAt(index,3);
          String Contactno = (String)tm.getValueAt(index,4);
       
          txt_Rollno.setText(Rollno);
          txt_Name.setText(Name);
          txt_Fname.setText(Fname);
          txt_Contactno.setText(Contactno);
          
        
        }
        catch(Exception e)
        {
        e.printStackTrace();
        }   
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
         try
        {
         String SectionName=(String)cmb_SectionName.getSelectedItem();  
        
        
        String Rollno=txt_Rollno.getText();
         String Name=txt_Name.getText();
          String Fname=txt_Fname.getText();
           String Contactno=txt_Contactno.getText();
         int Sectionindex=cmb_SectionName.getSelectedIndex();
            String x1[]=(String []) Sectiondata.get(Sectionindex);
            String SectionId=x1[0];
        
        String query2="update student set rollno=?,section_id=?,name=?,fname=?,contactno=? where rollno=?";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,Rollno);
        ps2.setString(2,SectionId);
        ps2.setString(3,Name);
        ps2.setString(4,Fname);
        ps2.setString(5,Contactno);
         ps2.setString(6,Rollno);
        
        int chk=ps2.executeUpdate();
        JOptionPane.showMessageDialog(this,"Data modified");
        showdata();
        
        
        
        }
        catch(Exception e)
        {
        e.printStackTrace();
         JOptionPane.showMessageDialog(this,"Data can't be modified"+e.getMessage());
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
         try
        {
       String Rollno=txt_Rollno.getText();
        String query="delete from student where rollno=?";
        PreparedStatement ps=x.prepareStatement(query);
        ps.setString(1,Rollno);
        int chk=ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"Data deleted");
        showdata();
        }
        catch(Exception e)
        {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,"Data cant be deleted");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void cmb_BatchNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_BatchNameItemStateChanged
        // TODO add your handling code here:
         try
        {
            cmb_SectionName.removeAllItems();
            Sectiondata.clear();
            String BatchId=null;
            String BatchName=(String) cmb_BatchName.getSelectedItem();
        String query="select batch_id from batch where batch_name=?";
        PreparedStatement ps=x.prepareStatement(query);
        ps.setString(1,BatchName);
        ResultSet rs=ps.executeQuery();
        if(rs.next())
        {
        BatchId=rs.getString("batch_id");
         
        }
         String query2="select * from section where batch_id=?";
        PreparedStatement ps2=x.prepareStatement(query2);
        ps2.setString(1,BatchId);
        ResultSet rs2=ps2.executeQuery();
        while(rs2.next())
        {
           String SectionId=rs2.getString("section_id");
            String SectionName=rs2.getString("section_name");
            String x1[]=new String[2];
            x1[0]=SectionId;
            x1[1]=SectionName;
            Sectiondata.add(x1);
        cmb_SectionName.addItem(SectionName);
        }
        
        
        
        }
        
    catch(Exception e)
    {
    e.printStackTrace();
    }
    }//GEN-LAST:event_cmb_BatchNameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JLabel Name;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JComboBox<String> cmb_BatchName;
    private javax.swing.JComboBox<String> cmb_CourseName;
    private javax.swing.JComboBox<String> cmb_DeptName;
    private javax.swing.JComboBox<String> cmb_SectionName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Contactno;
    private javax.swing.JTextField txt_Fname;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Rollno;
    // End of variables declaration//GEN-END:variables
}
